version: '2'
services:

    # dcr is an image of decred node which is used as base image for dcrd and
    # dcrlncli. The environment variables default values determined on stage of
    # container start within starting script.
    dcr:
      image: dcrd
      build:
        context: dcrd/
      volumes:
            - shared:/rpc
            - decred:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    dcrd:
        extends: dcr
        container_name: dcrd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-dcrd.sh"]

    dcrctl:
        extends: dcr
        container_name: dcrctl
        links:
            - "dcrd:rpcserver"
        entrypoint: ["./start-dcrctl.sh"]

    dcrlnd:
        image: dcrlnd
        build:
          context: ../
          dockerfile: docker/dcrlnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-dcrlnd.sh"]

    lnd_dcr:
      extends: dcrlnd
      container_name: lnd_dcr
      links:
          - "dcrd:blockchain"

volumes:
  # shared volume is need to store the dcrd rpc certificates and use it within
  # dcrctl and dcrlnd containers.
  shared:
    driver: local

  # decred volume is needed for maintaining blockchain persistence
  # during dcrd container recreation.
  decred:
    driver: local
